spring.application.name=alazani

spring.datasource.url=jdbc:h2:./data/alazani-db
spring.datasource.driverClassName=org.h2.Driver

# so that database is static between runs
spring.jpa.hibernate.ddl-auto=update